// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhIAheRFeQ4vmvnWettzsHWaJZq9Y60B4',
    appId: '1:881494930489:web:dab0a297c7306d736109e8',
    messagingSenderId: '881494930489',
    projectId: 'nayiswflut',
    authDomain: 'nayiswflut.firebaseapp.com',
    storageBucket: 'nayiswflut.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMVt56N38fN-WItQvgo0cDjWk5S5NRhLI',
    appId: '1:881494930489:android:c981543b88610a326109e8',
    messagingSenderId: '881494930489',
    projectId: 'nayiswflut',
    storageBucket: 'nayiswflut.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_hsNxxrqNS8V9DzZjdaVfIrKSdNZwFdg',
    appId: '1:881494930489:ios:75306b00679a84036109e8',
    messagingSenderId: '881494930489',
    projectId: 'nayiswflut',
    storageBucket: 'nayiswflut.appspot.com',
    iosBundleId: 'com.example.nayiswflut',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_hsNxxrqNS8V9DzZjdaVfIrKSdNZwFdg',
    appId: '1:881494930489:ios:bbe2deed37af1fe06109e8',
    messagingSenderId: '881494930489',
    projectId: 'nayiswflut',
    storageBucket: 'nayiswflut.appspot.com',
    iosBundleId: 'com.example.nayiswflut.RunnerTests',
  );
}
